//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AD.Svs.Web.SyncDB.DataServices.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SyncDBEngineeringData_R : DbContext
    {
        public SyncDBEngineeringData_R()
            : base("name=SyncDBEngineeringData_R")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HiPotTest> HiPotTest { get; set; }
        public virtual DbSet<iv_all> iv_all { get; set; }
        public virtual DbSet<iv_berger> iv_berger { get; set; }
        public virtual DbSet<iv_rel> iv_rel { get; set; }
        public virtual DbSet<iv_rel1> iv_rel1 { get; set; }
        public virtual DbSet<iv_prism> iv_prism { get; set; }
    }
}
