//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AD.Svs.Web.SyncDB.DataServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HiPotTest
    {
        public string UnitIdentifier { get; set; }
        public string Hipot_Version { get; set; }
        public Nullable<System.DateTime> Hipot_DateTime { get; set; }
        public string OperatorName { get; set; }
        public string RecipeName { get; set; }
        public string TestResultPassFail { get; set; }
        public System.DateTime InsertDateTime { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
    }
}
