//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AD.Svs.Web.SyncDB.DataServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class iv_all
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public System.DateTime Date { get; set; }
        public double Isc { get; set; }
        public double Voc { get; set; }
        public double Imp { get; set; }
        public double Vmp { get; set; }
        public double FF { get; set; }
        public double Pmp { get; set; }
        public double Eff { get; set; }
        public double Area { get; set; }
        public double Von { get; set; }
        public double Ibd { get; set; }
        public double Vbd { get; set; }
        public double Jsc { get; set; }
        public double Jmp { get; set; }
        public double Rs { get; set; }
        public double Rsh { get; set; }
        public string Wafer { get; set; }
        public string Cell { get; set; }
        public string Location_flow { get; set; }
        public string SystemID { get; set; }
        public string Test_recipe { get; set; }
    }
}
