//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AD.Svs.Web.SyncDB.DataServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class iv_berger
    {
        public int id { get; set; }
        public string Lot { get; set; }
        public string Module { get; set; }
        public string SN { get; set; }
        public double Active_Area { get; set; }
        public double Mesa_Area { get; set; }
        public double Total_Area { get; set; }
        public double R_sh { get; set; }
        public double R_s { get; set; }
        public double V_on { get; set; }
        public double J_01 { get; set; }
        public double J_02 { get; set; }
        public double J_dark___0_8V { get; set; }
        public double J_sc_active { get; set; }
        public double J_sc_mesa { get; set; }
        public double J_sc_total { get; set; }
        public double V_oc { get; set; }
        public double FF { get; set; }
        public double Eff_active { get; set; }
        public double Eff_mesa { get; set; }
        public double Eff_total { get; set; }
        public double J_mp_active { get; set; }
        public double J_mp_mesa { get; set; }
        public double J_mp_total { get; set; }
        public double V_max { get; set; }
        public string Operator { get; set; }
        public System.DateTime Date { get; set; }
        public string SystemID { get; set; }
        public string Test_recipe { get; set; }
        public double Temperature { get; set; }
        public string Location_flow { get; set; }
        public string Mask_ID { get; set; }
        public string Coordinate_system { get; set; }
        public string Cell_status { get; set; }
        public string Comment { get; set; }
        public double Contact_R_P { get; set; }
        public double Contact_R_N { get; set; }
        public double Isc { get; set; }
        public double Imax { get; set; }
        public string kind { get; set; }
    }
}
