//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AD.Svs.Web.SyncDB.DataServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class iv_prism
    {
        public string Wafer { get; set; }
        public string Step { get; set; }
        public string Cell { get; set; }
        public string Owner { get; set; }
        public string Purpose { get; set; }
        public string Flow { get; set; }
        public string Bin { get; set; }
        public Nullable<System.DateTime> screen_date { get; set; }
        public Nullable<System.DateTime> Prism_date { get; set; }
        public Nullable<System.DateTime> TestDate { get; set; }
        public Nullable<System.DateTime> DATime_date { get; set; }
        public string Epi_run_number { get; set; }
        public Nullable<float> Rs { get; set; }
        public Nullable<float> Vp { get; set; }
        public Nullable<float> Np { get; set; }
        public Nullable<float> Vp_Indoor { get; set; }
        public Nullable<float> Np_Indoor { get; set; }
        public Nullable<float> Loss_Rs { get; set; }
        public Nullable<float> Rs_Jsc { get; set; }
        public Nullable<float> Jsc_Dark { get; set; }
        public Nullable<float> G_Rev { get; set; }
        public Nullable<float> Pre_Rs { get; set; }
        public Nullable<float> Pre_Vp { get; set; }
        public Nullable<float> Pre_Np { get; set; }
        public Nullable<float> Pre_Vp_Indoor { get; set; }
        public Nullable<float> Pre_Np_Indoor { get; set; }
        public Nullable<float> Pre_Loss_Rs { get; set; }
        public Nullable<float> Pre_Rs_Jsc { get; set; }
        public Nullable<float> Pre_G_Rev { get; set; }
        public Nullable<float> BD_G_BD { get; set; }
        public Nullable<float> BD_G_Rev { get; set; }
        public Nullable<float> Eff_DATIME { get; set; }
        public Nullable<float> Jsc_Active { get; set; }
        public Nullable<float> FF { get; set; }
        public Nullable<float> Von { get; set; }
        public Nullable<float> Voc { get; set; }
        public Nullable<float> Eff_Active { get; set; }
        public Nullable<float> J_Dark { get; set; }
        public Nullable<float> Pre_Eff_DATIME { get; set; }
        public Nullable<float> Pre_Jsc_Active { get; set; }
        public Nullable<float> Pre_FF { get; set; }
        public Nullable<float> Pre_Von { get; set; }
        public Nullable<float> Pre_Voc { get; set; }
        public Nullable<float> Pre_Eff_Active { get; set; }
        public Nullable<float> Pre_Jsc_Dark { get; set; }
        public Nullable<float> Vbd { get; set; }
    }
}
