//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AD.Svs.Web.SyncDB.DataServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class iv_rel1
    {
        public System.DateTime rel_date { get; set; }
        public string Step { get; set; }
        public string Wafer { get; set; }
        public string Cell { get; set; }
        public double Voc_Percent { get; set; }
        public double Isc_Percent { get; set; }
        public double FF_Percent { get; set; }
        public double Eff_Percent { get; set; }
        public double Gsh_Delta { get; set; }
        public double Rs_Delta { get; set; }
        public double Vp_Percent { get; set; }
        public Nullable<double> Eff { get; set; }
        public Nullable<double> Vbd { get; set; }
        public Nullable<double> Gsh { get; set; }
        public string Bin { get; set; }
        public string optical { get; set; }
        public string pl { get; set; }
    }
}
